title: one to be taken daily photoblog
description: A simple photoblog powered by Jekyll.
author: Larrie Knights
url: "https://your-username.github.io/your-repo-name" # Replace with your GitHub Pages URL